# Generated by Django 4.2.2 on 2023-12-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('task', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('completion_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
